name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
    group: ${{ github.repository }}-${{ github.event.ref }}
    cancel-in-progress: true    

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Run cargo check
        run: cargo check --verbose

  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout sources      
      - uses: actions/checkout@v3

      - name: Build
        run: cargo build --release --verbose

      - name: Packing TAR
        run: |
          cd target/release
          chmod +x ./p3d-pool-proxy
          tar -czf p3d-pool-proxy_linux.tar.gz ./p3d-pool-proxy

      - name: Create Release
        uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: |
            target/release/p3d-pool-proxy_linux.tar.gz
          draft: true
          prerelease: false
          skipIfReleaseExists: true
          artifactErrorsFailBuild: true
          tag: latest-${{ github.event.ref }}

